#!/bin/bash
# iperf testing script

# is localhost server?
LOCALHOST=true

# default port = 5001
port=5002

# 6.5ms from hotel.futuregrid.org
#server=india.futuregrid.org 
server=login2.uc.futuregrid.org 
client=india.futuregrid.org 
#server=localhost

# 28ms from hotel.futuregrid.org
#server=alamo.futuregrid.org 

# 76ms from hotel.futuregrid.org
#server=sierra.futuregrid.org 

# RTT (ms), LAN=0.3-0.5ms
# IMPORTANT: RTT should be halved later
#RTTs=( 160 ) # 40tcps failed
#RTTs=( 20 60 10 140 160 ) # 30tcp failed
RTT=76
#RTTs=( 76 )
#RTTs=( LAN 2 5 10 20 80 180 )

#runs=( 1 2 3 4 5 6 7 8 9 10 )
runs=( 2 3 4 5 6 7 8 9 10 )
#runs=( 21 22 23 24 25 26 27 28 29 30 )
# failed
#runs=( 23 ) 
#run=12

# number of parallel TCP connections
#Ns=( 1 2 3 4 5 6 7 8 9 10 12 14 16 18 20 )
Ns=( 1 2 3 4 5 6 7 8 9 10 12 14 16 18 20 30 40 50 60 70 80 90 100 )
#Ns=( 1 2 )
#Ns=( 30 40 )

# total run time in seconds
totaltime=60
#totaltime=120

#ssh $server iperf3 -s > server.log &

if $LOCALHOST; then
	echo localhost is server
	pkill iperf  
	iperf -s -p $port > server.log &
else
	ssh $server pkill iperf  
	ssh $server iperf -s -p $port &
fi

sleep 3

#for RTT in ${RTTs[@]};
for run in ${runs[@]};
do
	#echo RTT = ${RTT}ms

	#logfile=${RTT}ms-r${run}.log
	logfile=r${run}.log
	rm $logfile

	echo -n "Run = $run: "
	for N in ${Ns[@]}
	do
		echo -n "$N "
		echo N = $N >> $logfile
		#iperf3 -c $server -P $N -t 30 -O 45 >> $logfile
		if $LOCALHOST; then
			echo ssh $client iperf -c $server -p $port -P $N -t $totaltime
			ssh $client iperf -c $server -p $port -P $N -t $totaltime >> $logfile
		else
			iperf -c $server -P $N -p $port -t $totaltime >> $logfile
		fi
	done
#	ssh $router service tc stop
	echo
done

#echo

# stop iperf
if $LOCALHOST; then
	pkill iperf
else 
	ssh $server pkill iperf
fi

