#!/bin/bash
# iperf testing script

# is localhost server?
#LOCALHOST=true
LOCALHOST=false

# default port = 5001
port=5001
#port=5002

# 104ms from foxtrot
#server=sierra.futuregrid.org

# 56ms to alamo
RTT=56ms
prefix=alamo
server=$prefix.futuregrid.org 

# 35ms to india
#server=india.futuregrid.org 
#server=login2.uc.futuregrid.org 
#client=india.futuregrid.org 

# 30ms to hotel

sshserver=david78k@$server

# RTT (ms), LAN=0.3-0.5ms
# IMPORTANT: RTT should be halved later
#RTTs=( 160 ) # 40tcps failed
#RTTs=( 20 60 10 140 160 ) # 30tcp failed
RTT=76
#RTTs=( 76 )
#RTTs=( LAN 2 5 10 20 80 180 )

runs=( 1 2 3 4 5 6 7 8 9 10 )
#runs=( 2 3 4 5 6 7 8 9 10 )
#runs=( 21 22 23 24 25 26 27 28 29 30 )
#runs=( 14 15 16 17 18 19 20 ) 
#run=12

# number of parallel TCP connections
#Ns=( 1 2 3 4 5 6 7 8 9 10 12 14 16 18 20 )
Ns=( 1 2 3 4 5 6 7 8 9 10 12 14 16 18 20 30 40 50 60 70 80 90 100 )
#Ns=( 1 2 3 4 5 )
#Ns=( 6 7 8 9 10 12 14 16 18 20 30 40 50 60 70 80 90 100 )

# total run time in seconds
#totaltime=30
totaltime=60
#totaltime=120

logdir="${server}-$RTT"

mkdir -p $logdir

#ssh $server iperf3 -s > server.log &

if $LOCALHOST; then
	echo localhost is server
	pkill iperf  
	#logsave server.log iperf -s -p $port &
	iperf -s -p $port > server.log &
else
	ssh $sshserver pkill iperf  
	ssh $sshserver iperf -s -p $port > /dev/null &
fi

sleep 3

#for RTT in ${RTTs[@]};
for run in ${runs[@]};
do
	#echo RTT = ${RTT}ms

	#logfile=${RTT}ms-r${run}.log
	logfile=$logdir/r${run}.log
	rm $logfile

	echo -n "Run = $run: "
	for N in ${Ns[@]}
	do
		echo -n "$N "
		echo N = $N >> $logfile
		
		cmd="iperf -c $server -P $N -p $port -t $totaltime -i 1 -fM"

		#iperf3 -c $server -P $N -t 30 -O 45 >> $logfile
		if $LOCALHOST; then
			echo ssh $client iperf -c $server -p $port -P $N -t $totaltime
			ssh $client $cmd >> $logfile
			#ssh $client iperf -c $server -p $port -P $N -t $totaltime >> $logfile
		else
			iperf -c $cmd >> $logfile
			#iperf -c $server -P $N -p $port -t $totaltime >> $logfile
		fi
	done
#	ssh $router service tc stop
	echo
done

#echo

# stop iperf
if $LOCALHOST; then
	pkill iperf
else 
	ssh $sshserver pkill iperf
fi

